add polymorphism exercises
kipijz/java-homework pull request #10
Opened 2022-03-25 18:09 UTC by kipijz

2022-04-21 20:05 UTC, NilsKula requested changes

2022-04-21 20:05 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/Animal.java
> +    DecimalFormat decimalFormat = new DecimalFormat("0.#");
this can be constant

2022-04-21 20:05 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/Main.java
> +    private static boolean checkFood() {
šo validāciju būtu labāk ieviest katra dzīvnieka klasē, jo zebra jau vienmēr neēdīs gaļu un to vajadzētu redzēt jebkur, kur izmanto zebras klasi

2022-04-24 11:05 UTC, kipijz commented
paldies, izlabots!

2022-04-24 13:26 UTC, NilsKula approved these changes

2022-04-24 14:21 UTC, merged