finish flowcontrol & loops
kipijz/java-homework pull request #2
Opened 2022-02-28 09:23 UTC by kipijz

2022-03-06 21:06 UTC, NilsKula requested changes

2022-03-06 21:06 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +        return (int) ((Math.random() * 6) + 1);
izmanto Random.nextInt(), unnecessary complexity un no casting labāk izvairīties pēc iespējas 
un metode var but private

2022-03-06 21:06 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +                    points = 0;
nav nepieciešams vairs updeitot poitn value, pēc šī ir exit un vērtība vairs nekur nav nepieciešama tālāk

2022-03-06 21:06 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise8.java
> +            for (int forward = size * 4 - 4; forward > rows * 4; forward--) {
ūtu labi arī definēt vārdos šos ciparus 4 un 8 etc

2022-03-06 21:06 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +                secondRoll = diceRoll.nextInt(6) + 1;
šis atkārtojas vairākārt, varētu arī izvilkt uz atsevišķu metodi, kā jau darīji citos uzdevumos

2022-03-08 09:41 UTC, kipijz commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +                secondRoll = diceRoll.nextInt(6) + 1;
veicu visas izmaiņas un it kā commit & push, ceru, ka visu pareizi izdarīju saistībā ar github? vienīgi šim Exercise9 nevarēju atkost kā pilnīgi visu koda bloku ielikt iekšā metodē, jo metodei vajadzētu atgriezt 2 int vērtības, bet tas nav iespējams?

2022-03-08 16:21 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +                secondRoll = diceRoll.nextInt(6) + 1;
viss ok ar labojumiem, approved
un par metodi abus noteikti nevajadzēja vienā, tā arī biju domājis, kā uztaisīji ar `roll()`

2022-03-08 16:21 UTC, NilsKula approved these changes

2022-03-09 09:37 UTC, merged