Date and time
kipijz/java-homework pull request #5
Opened 2022-03-14 17:05 UTC by kipijz

2022-03-23 08:37 UTC, NilsKula requested changes

2022-03-23 08:37 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise1/Exercise1Test.java
> +    public static LocalDate addDate(Scanner scan) {
private

2022-03-23 08:37 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise1/Work.java
> +        final int WORKED_HOURS = 8;
static

2022-03-23 08:37 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise1/Work.java
> +            if (date.getDayOfWeek() != DayOfWeek.SATURDAY && date.getDayOfWeek() != DayOfWeek.SUNDAY) {
varētu uz palīgmetodi
`if(isWorkDay())` for example

2022-03-23 08:37 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise2/Exercise2Test.java
> +    public static boolean checkUpdateDate(String updateYear, String updateMonth, LocalDate serverLaunchDay) {
private

2022-03-23 08:37 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise3/DatePeriod.java
> +        startDateForIntersection = findStartDate(listOfDates, listOfDatesPassed, startDateForIntersection);
`LocalDate startDateForIntersection = findStartDate(listOfDates, listOfDatesPassed, startDateForIntersection);`
vari uzreiz šādi un izlaist rindiņu apzīmēšanai ar null

2022-03-23 14:58 UTC, kipijz commented on src/main/java/io/codelex/dateandtime/exercises/exercise3/DatePeriod.java
> +        startDateForIntersection = findStartDate(listOfDates, listOfDatesPassed, startDateForIntersection);
Čau, visu izdarīju izņemot šo. Ja es uzreiz `startDateForIntersection` definēju bez null, viņš man met erroru "might not have been initialized". It kā varētu no `findEndDate` funkcijas noņemt to `startDateForIntersection` argumentu un tad iekš pašas funkcijas likt `startDateForIntersection`, bet tur arī vajadzēs virspirms apzīmēt kā null 🤔
https://i.imgur.com/7aIS1XV.png

2022-03-24 22:19 UTC, NilsKula commented on src/main/java/io/codelex/dateandtime/exercises/exercise3/DatePeriod.java
> +        startDateForIntersection = findStartDate(listOfDates, listOfDatesPassed, startDateForIntersection);
jā, es vainīgs, nemaz nepamanīju, ka tiek padots vēl metodē
un tieši tā, labāk tad noņēmt no funkcijas, noteikti nav jēgas padot argumentu kurš vienmēŗ būs null :+1:

2022-03-24 22:20 UTC, NilsKula approved these changes

2022-03-26 18:44 UTC, merged