finish oop exercises
kipijz/java-homework pull request #6
Opened 2022-03-15 11:15 UTC by kipijz

2022-03-29 21:04 UTC, NilsKula requested changes

2022-03-29 21:04 UTC, NilsKula commented on src/main/java/io/codelex/oop/parcels/Parcel.java
> +    private static final int MAX_COMBINED_DIMENSIONS = 300;
static pirms visa pārēja klasē

2022-03-29 21:04 UTC, NilsKula commented on src/main/java/io/codelex/oop/persons/Customer.java
> +public class Customer extends Person{
`ctrl + alt + L`

2022-03-29 21:04 UTC, NilsKula commented on src/main/java/io/codelex/oop/runners/Runner.java
> +        if (userRunInput <= ADVANCED.maxMarathonRunTime && userRunInput >= ADVANCED.minMarathonRunTime) {
šos ar varbūt var izvilkt uz palīgmetodēm `if(isAdvanced())`

2022-03-29 21:04 UTC, NilsKula commented on src/main/java/io/codelex/oop/shapes/Shape.java
> +    int numSides;
private ja jau ir getteris?

2022-03-30 11:30 UTC, kipijz commented on src/main/java/io/codelex/oop/cars/CarService.java
> +            for (Manufacturer manufacturer : car.getManufacturers()) {
Veicu visas izmaiņas izņemot šo, pie šī kādu laiku pasēdēju un galu galā īsti nesapratu, kā tos for loopus ielikt iekš `Cars ` klases. Vari nedaudz plašāk aprakstīt?

2022-04-10 07:04 UTC, janistumpelis approved these changes

2022-04-11 11:24 UTC, merged