finish enums_and_maps
kipijz/java-homework pull request #7
Opened 2022-03-22 12:02 UTC by kipijz

2022-03-24 20:41 UTC, NilsKula requested changes
👍

2022-03-24 20:41 UTC, NilsKula commented on src/main/java/io/codelex/enums/exercise1/CardinalPoints.java
> +    private String direction;
šī vietā var izmantot pašu enum vērtību and convert it with built in string method

2022-03-24 20:41 UTC, NilsKula commented on src/main/java/io/codelex/enums/exercise2/Game.java
> +        MutableInt userWins = new MutableInt(0);
kādēļ MutableInt? 🤔 
šķiet jau ka `int` would do the job perfectly fine as well

2022-03-24 20:41 UTC, NilsKula commented on src/main/java/io/codelex/enums/exercise2/Game.java
> +                //computer turn
ja gribas likt komentāru, aizvieto ar palīgmetodi
`computerTurn(...)` 😄

2022-03-28 10:32 UTC, kipijz commented on src/main/java/io/codelex/enums/exercise2/Game.java
> +                //computer turn
paldies, veicu visas izmaiņas 🤠

2022-03-30 12:12 UTC, merged