finish exceptions
kipijz/java-homework pull request #8
Opened 2022-03-22 16:10 UTC by kipijz

2022-03-30 21:03 UTC, NilsKula requested changes

2022-03-30 21:03 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +        } catch (ArithmeticException e) {
`After each try{} block put a catch{} block which catches the exception, prints a stack trace, and throws the exception object to its caller`

2022-04-01 11:58 UTC, kipijz commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +        } catch (ArithmeticException e) {
izlaboju

2022-04-15 16:58 UTC, NilsKula approved these changes

2022-04-21 12:40 UTC, merged