finish collections
kipijz/java-homework pull request #9
Opened 2022-03-25 11:35 UTC by kipijz

2022-04-10 14:14 UTC, NilsKula requested changes
👍

2022-04-10 14:14 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +    private static final Charset charset = Charset.defaultCharset();
static final in caps

2022-04-10 14:14 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +            if (Integer.parseInt(s) <= 19 && Integer.parseInt(s) >= 10) {
pietiek ar `Integer.parseInt(s) <= 19`, zini jau ka nav zem 10

2022-04-10 14:14 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
private

2022-04-11 11:22 UTC, kipijz commented
paldies, izlabots

2022-04-15 17:44 UTC, NilsKula approved these changes

2022-04-22 08:02 UTC, NilsKula approved these changes
merge it :+1:

2022-04-24 07:14 UTC, janistumpelis approved these changes

2022-04-24 10:35 UTC, merged